export const RECEIVE_ALL = 'RECEIVE_ALL';
export const RECEIVE_ARTICLE = 'RECEIVE_ARTICLE';
export const ADD_ARTICLE = 'ADD_ARTICLE';
export const EDIT_ARTICLE = 'EDIT_ARTICLE';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';